Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    puppet.vm.box  = "centos/7"
    puppet.vm.hostname = "puppet.example.com"
    puppet.vm.network :private_network, ip: "10.0.0.10"
    puppet.hostmanager.aliases = %w(puppet)
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos.example.com"
    centos.vm.network :private_network, ip: "10.0.0.11"
    centos.hostmanager.aliases = %w(centos)
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/jessie64"
    debian.vm.hostname = "debian.example.com"
    debian.vm.network :private_network, ip: "10.0.0.12"
    debian.hostmanager.aliases = %w(debian)
  end

end