source ENV['GEM_SOURCE'] || 'https://rubygems.org'

puppetversion = ENV.key?('PUPPET_VERSION') ? ENV['PUPPET_VERSION'] : ['>= 3.3']
# gem 'puppet', puppetversion
# gem 'facter', '>= 1.7.0'

group :test, :development do
  gem 'hiera-eyaml', '>= 2.1'
end